title: "Lalit Singh"
author: "Lalit Singh"
description: "Senior Data Engineer · Python · PySpark · AWS · GenAI"
theme: minima
url: "https://lalitsingh24x7.github.io"
baseurl: ""
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag